#!/bin/bash

# Import local private environment variables

export DOCKER_CONTAINER=jwt-demo-postgres
export DOCKER_POSTGRES_PORT=8999
export DOCKER_VOLUME_NAME=jwt-demo-postgres-pgdata
export DATABASE_NAME=jwt_demo

source ./local-env-private
